version: "3"
networks:
  proxy:
    external: true
  internal:
    external: false
services:
  app:
    container_name: twitter-bot
    restart: always
    networks:
      - internal
      - proxy
    build: ./
    labels:
      - traefik.backend=app
      - traefik.frontend.rule=Host:twit.nanomenta.fr
      - traefik.docker.network=proxy
      - traefik.port=3000
    volumes:
      - .:/app
      - /app/node_modules
    
